[General]
Input type=12098
Name of namefile=modpath.in
Output mode=2
Compute budget=0
Cell-by-cell check=0
Summarize final data=1
[Absolute time]
Time=0
TC factor=1
[Flow terms]
File type=1
Name=E:\Documents and Settings\tmartins\My Documents\Projectos\SRHE Pernambuco\Modelo_Centro_VMF\Modelo_Centro_v10_2013_2015_refinado\Corrida_52ipoj\Modelo_Centro_v10_2013_2015_refinado_corrida52.cbf
[Sinks]
How=3
Discharge percent=0.05
[Start location]
Forward from=1
Forward name=forward.in
Backward from=1
Backward name=backward.in
